Vagrant.configure("2") do |config|
  config.vm.box = "bento/rockylinux-9"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = 2
  end

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.define "vm1" do |vm1|
    vm1.vm.hostname = "rocky1"
    vm1.vm.network "private_network", ip: "192.168.56.10"
  end
end