// Blocco radice che apre la pipeline
pipeline {
    // Definisce su quale nodo far girare la pipeline, in questo caso su qualsiasi nodo che abbia il tag "build"
    agent { label 'build' }
    
    // Definisce variabili d'ambiente valide in tutta la pipeline. Ogni stage può accedere ai valori definiti attraverso l'oggetto env
    // L'oggetto env contiene sia le variabili di ambiente definite in environment, sia le variabili create automaticamente da jenkins
    environment {
        // Coordinate dell'immagine su Docker Hub.
        DOCKERHUB_USER = 'namanari36'
        IMAGE_REPO     = 'formazione_sou'
        IMAGE_NAME     = "${DOCKERHUB_USER}/${IMAGE_REPO}"

        // ID delle credenziali create a mano nella UI di Jenkins.
        DOCKERHUB_CREDS = 'dockerhub-credentials'
        // Percorso al Socket Podman dell'host con stringa URI, montato nell'agent (per DooD).
        CONTAINER_HOST = 'unix:///run/podman/podman.sock'
    }
    
    // Definisce i vari stage della pipeline, ogni stage presenta un nome ed è composto da vari steps
    stages {
        stage('Determina il tag immagine') {
            // Steps necessari per determinare quale tag dare all'immagine docker
            steps {
                //script apre una zona di script Groovy, utile in caso bisogni implementare una logica che la sintassi dichiarativa non permette
                script {
                    // Se esiste un TAG_NAME git allora il tag dell'immagine sarà lo stesso nome del tag git
                    if (env.TAG_NAME) {

                        env.IMAGE_TAG = env.TAG_NAME

                    // Se il branch è main, il tag dell'immagine sarà latest
                    } else if (env.BRANCH_NAME == 'main') {

                        env.IMAGE_TAG = 'latest'
                   
                    // Se branch è develop, il tag sarà develop- seguito dai primi 7 caratteri del SHA del commit
                    } else if (env.BRANCH_NAME == 'develop') {

                        env.IMAGE_TAG = "develop-${env.GIT_COMMIT.take(7)}"
                    
                    // Condizione che copre tutti gli altri casi, cioè un branch che non è ne main, ne develop
                    // Il tag dell'immagine docker prende il nome del branch come tag
                    } else {
 
                        env.IMAGE_TAG = env.BRANCH_NAME

                    }

                    // Print di debug
                    echo "Immagine: ${IMAGE_NAME}:${env.IMAGE_TAG}"
                }
            }
        }
        // Steps per buildare l'immagine sull'host (Dood)
        stage('Build immagine') {
            // Step che utilizza il comando sh per eseguire un comando shell sull'agent
            steps {
                // podman --remote build dice alla podman CLI di far eseguire la build all'host
                // la flag -t assegna il nome all'immagine
                // la flag -f segnala dove si trova il DockerFile
                sh '''
                    podman --remote build \
                        -t ${IMAGE_NAME}:${IMAGE_TAG} \
                        -f Dockerfile .
                '''
            }
        }
        
        // Steps per pushare l'immagine buildata su dockerhub
        stage('Push su Docker Hub') {
            steps {
                // Il blocco withCredentials associa in modo sicuro le credenziali memorizzate da Jenkins alle variabili d'ambiente, 
                // rendendo disponibili le variabili del segreto solo all'interno del suo scope
                // usernamePassword è un blocco che specifica il tipo di credenziali
                // usernameVariable e passwordVariable sono i due parametri propri del tipo usernamePassword che servono per assegnare il valore contenuto a delle variabili
                withCredentials([usernamePassword(
                    credentialsId: "${DOCKERHUB_CREDS}",
                    usernameVariable: 'REG_USER',
                    passwordVariable: 'REG_PASS'
                )]) {
                    // Step che utilizza il comando sh per eseguire il login e il push dell'immagine su dockerhub
                    sh '''  
                        echo "${REG_PASS}" | podman --remote login docker.io \
                            -u "${REG_USER}" --password-stdin
                        podman --remote push ${IMAGE_NAME}:${IMAGE_TAG}
                    '''
                }
            }
        }
    }

    // Il blocco post definisce azioni da eseguire dopo che tutti gli stage sono finiti.
    post {
        // always è è una delle condizioni predefinite del blocco post. Indica di eseguire il codice segnato all'interno nonostante l'esito dei stages
        always {
            // Comando di logout dalla sessione dockerhub
            sh 'podman --remote logout docker.io || true'
        }
    }
}